version: '2'

services:
  queuing:
    image: rabbitmq:latest
    container_name: rabbitQueue
    ports:
      - 5671:5671
      - 5672:5672
    environment:
      - RABBITMQ_HIPE_COMPILE= 1

  web:
    build: Web
    container_name: web
    ports:
      - 8080:8080
    depends_on:
      - queuing
      - draw
      - customer
      - notification
      - bet

  bet:
    build: BetService
    container_name: Bets
    depends_on:
       - queuing

  customer:
    build: Customer
    container_name: Customers
    depends_on:
       - queuing

  draw:
    build: DrawService
    container_name: Draws
    depends_on:
      - queuing

  notification:
    build: NotificationService
    container_name: Notification
    depends_on:
       - queuing
