version: '2'

services:
  queuing:
    image: rabbitmq:latest
    container_name: Queue
    ports:
      - 5671:5671
      - 5672:5672
    environment:
      - RABBITMQ_HIPE_COMPILE= 1

  web:
    build: Web
    container_name: Web
    ports:
      - 8080:8080
    depends_on:
      - queuing
      - draw
      - customer
      - notification
      - bet

  bet:
    build: BetService
    container_name: Bet
    depends_on:
       - queuing

  customer:
    build: Customer
    container_name: Customer
    depends_on:
       - queuing

  draw:
    build: DrawService
    container_name: Draw
    depends_on:
      - queuing

  notification:
    build: NotificationService
    container_name: Notification
    depends_on:
       - queuing
       - mail-server

  mail-server:
    image: mailhog/mailhog
    container_name: Mail
    ports:
       - 1025:1025
       - 8025:8025
