version: '2'

services:
  queue:
    image: rabbitmq:latest
    ports:
      - 5671:5671
      - 5672:5672
    environment:
      - RABBITMQ_HIPE_COMPILE= 1

  web:
    build: Web
    ports:
      - 9080:8080
    depends_on:
      - queue
      - draw
      - customer
      - notification
      - bet
    links:
      - queue  

  bet:
    build: BetService
    depends_on:
       - queue
    links:
       - queue

  customer:
    build: Customer
    depends_on:
       - queue
    links:
       - queue   

  draw:
    build: DrawService
    depends_on:
      - queue
    links:
      - queue  

  notification:
    build: NotificationService
    depends_on:
       - queue
       - mail-server
    links:
       - queue
       - mail-server   
       

  mail-server:
    image: mailhog/mailhog
    ports:
       - 1025:1025
       - 8025:8025
